# Generated by Django 6.0.4 on 2026-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
