# Generated by Django 6.0.4 on 2026-05-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_prueba_activate_alter_prueba_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'ordering': ['titulo'], 'verbose_name': 'Prueba', 'verbose_name_plural': 'Lista Prueba'},
        ),
    ]
